const express = require('express')
const router = express.Router()
const authController = require('../controllers/auth') 
const homeController = require('../controllers/home')
const userProfileController = require('../controllers/userProfile')
const userShowsController = require('../controllers/userShows')
const aboutController = require('../controllers/about')
const contactController = require('../controllers/contact')
const cartController = require('../controllers/cart')
const { ensureAuth, ensureGuest } = require('../middleware/auth')

router.get('/', homeController.getIndex)
router.get('/userProfile', ensureAuth, userProfileController.getIndex)
router.get('/userShows', ensureAuth, userShowsController.getUserShows)
router.get('/about', aboutController.getIndex)
router.get('/contact', contactController.getIndex)
router.get('/cart', cartController.getIndex)
router.get('/login', authController.getLogin)
router.post('/login', authController.postLogin)
router.get('/logout', authController.logout)
router.get('/signup', authController.getSignup)
router.post('/signup', authController.postSignup)

module.exports = router